### ISSUE TITLE
precise32 or precise64

### ISSUE THREAD

**Issue by webhat** [basho-labs/riak-ruby-vagrant#1]
The `README.md` points to documentation which suggests using `http://files.vagrantup.com/precise32.box` and the `Vagrantfile` uses `http://files.vagrantup.com/precise64.box`.

**EDIT**: the only thing that needs to be done in step 2 is run `vagrant up`.

**Comment by mjbrender** [comment]
Some time between this issue and today this was resolved. Thanks @webhat :tada:

**Comment by webhat** [comment]
:rabbit: :+1:
